### ISSUE TITLE
Loops in a transaction

### ISSUE THREAD

**Issue by ankuragrwl** [xiaoerge/X12Healthcare#1]
I need to parse loops in the transaction.
How can I achieve this by using your library?
Please help

**Comment by xiaoerge** [comment]
Yes,  it does allow multiple information sources in a transaction.

**Comment by ankuragrwl** [comment]
yes I got it. Thanks.

Are you still actively working on other files support as well ?

**Comment by xiaoerge** [comment]
Yes. This project is still on going.
